// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: livekit_agent_dispatch_queue.proto

package livekit

import (
	_ "github.com/livekit/protocol/livekit/logger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueuedJobStatus int32

const (
	QueuedJobStatus_QUEUED_JOB_STATUS_UNSPECIFIED QueuedJobStatus = 0
	// Awaiting capacity, or waiting on start_after.
	QueuedJobStatus_QUEUED_JOB_STATUS_QUEUED QueuedJobStatus = 1
	// Admitted; CreateDispatch in flight.
	QueuedJobStatus_QUEUED_JOB_STATUS_DISPATCHING QueuedJobStatus = 2
	// Dispatch created, agent job live.
	QueuedJobStatus_QUEUED_JOB_STATUS_RUNNING   QueuedJobStatus = 3
	QueuedJobStatus_QUEUED_JOB_STATUS_SUCCEEDED QueuedJobStatus = 4
	QueuedJobStatus_QUEUED_JOB_STATUS_FAILED    QueuedJobStatus = 5
	// Removed, or cancelled with its group, before it was admitted.
	QueuedJobStatus_QUEUED_JOB_STATUS_CANCELLED QueuedJobStatus = 6
	// Still queued at expires_at; never dispatched. Includes a job whose
	// start_after never arrived before it expired.
	QueuedJobStatus_QUEUED_JOB_STATUS_EXPIRED QueuedJobStatus = 7
)

// Enum value maps for QueuedJobStatus.
var (
	QueuedJobStatus_name = map[int32]string{
		0: "QUEUED_JOB_STATUS_UNSPECIFIED",
		1: "QUEUED_JOB_STATUS_QUEUED",
		2: "QUEUED_JOB_STATUS_DISPATCHING",
		3: "QUEUED_JOB_STATUS_RUNNING",
		4: "QUEUED_JOB_STATUS_SUCCEEDED",
		5: "QUEUED_JOB_STATUS_FAILED",
		6: "QUEUED_JOB_STATUS_CANCELLED",
		7: "QUEUED_JOB_STATUS_EXPIRED",
	}
	QueuedJobStatus_value = map[string]int32{
		"QUEUED_JOB_STATUS_UNSPECIFIED": 0,
		"QUEUED_JOB_STATUS_QUEUED":      1,
		"QUEUED_JOB_STATUS_DISPATCHING": 2,
		"QUEUED_JOB_STATUS_RUNNING":     3,
		"QUEUED_JOB_STATUS_SUCCEEDED":   4,
		"QUEUED_JOB_STATUS_FAILED":      5,
		"QUEUED_JOB_STATUS_CANCELLED":   6,
		"QUEUED_JOB_STATUS_EXPIRED":     7,
	}
)

func (x QueuedJobStatus) Enum() *QueuedJobStatus {
	p := new(QueuedJobStatus)
	*p = x
	return p
}

func (x QueuedJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueuedJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_livekit_agent_dispatch_queue_proto_enumTypes[0].Descriptor()
}

func (QueuedJobStatus) Type() protoreflect.EnumType {
	return &file_livekit_agent_dispatch_queue_proto_enumTypes[0]
}

func (x QueuedJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueuedJobStatus.Descriptor instead.
func (QueuedJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{0}
}

// Which slice of the project's queued traffic a DispatchLimit applies to.
type DispatchLimitScope int32

const (
	// The project's whole queue.
	DispatchLimitScope_DISPATCH_LIMIT_SCOPE_UNSPECIFIED DispatchLimitScope = 0
	// QueuedJobInput.agent_name.
	DispatchLimitScope_DISPATCH_LIMIT_SCOPE_AGENT DispatchLimitScope = 1
	// The QueuedJobInput.labels entry named by DispatchLimit.label.
	DispatchLimitScope_DISPATCH_LIMIT_SCOPE_LABEL DispatchLimitScope = 2
)

// Enum value maps for DispatchLimitScope.
var (
	DispatchLimitScope_name = map[int32]string{
		0: "DISPATCH_LIMIT_SCOPE_UNSPECIFIED",
		1: "DISPATCH_LIMIT_SCOPE_AGENT",
		2: "DISPATCH_LIMIT_SCOPE_LABEL",
	}
	DispatchLimitScope_value = map[string]int32{
		"DISPATCH_LIMIT_SCOPE_UNSPECIFIED": 0,
		"DISPATCH_LIMIT_SCOPE_AGENT":       1,
		"DISPATCH_LIMIT_SCOPE_LABEL":       2,
	}
)

func (x DispatchLimitScope) Enum() *DispatchLimitScope {
	p := new(DispatchLimitScope)
	*p = x
	return p
}

func (x DispatchLimitScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchLimitScope) Descriptor() protoreflect.EnumDescriptor {
	return file_livekit_agent_dispatch_queue_proto_enumTypes[1].Descriptor()
}

func (DispatchLimitScope) Type() protoreflect.EnumType {
	return &file_livekit_agent_dispatch_queue_proto_enumTypes[1]
}

func (x DispatchLimitScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchLimitScope.Descriptor instead.
func (DispatchLimitScope) EnumDescriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{1}
}

// What to dispatch. Mirrors CreateAgentDispatchRequest so that a queued job and
// an immediate dispatch describe the same work.
type QueuedJobInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must match the agent_name registered by the agent server.
	AgentName string `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	// Required. The queue does not invent room names; a caller wanting one room
	// per job supplies its own unique name.
	RoomName string `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// Required, unique per project. Re-adding with the same key returns the
	// existing job rather than dispatching twice.
	IdempotencyKey string            `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       string            `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attributes     map[string]string `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Deployment     string            `protobuf:"bytes,6,opt,name=deployment,proto3" json:"deployment,omitempty"`
	RestartPolicy  JobRestartPolicy  `protobuf:"varint,7,opt,name=restart_policy,json=restartPolicy,proto3,enum=livekit.JobRestartPolicy" json:"restart_policy,omitempty"`
	// Never dispatch after this time; the job goes to EXPIRED instead. Capped at
	// 8 days out to stay inside the row retention window, which also bounds
	// start_after.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	// Per-job callbacks, signed with the project key, as with Egress per-request
	// webhooks. Project-level webhooks fire regardless.
	Webhooks []*WebhookConfig `protobuf:"bytes,9,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	// Classification labels, used to scope DispatchLimits. Not forwarded to the
	// agent - use attributes for that.
	//
	// Values must name a class, never an identity: "insurer":"acme-health" is
	// right, a phone number is not. Identities make the label set grow with the
	// job set and put PII in a configuration surface.
	Labels map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Hold the job until this time. A floor, not an appointment: the job still
	// waits on capacity once eligible, and eligibility only filters the FIFO
	// scan - order stays created_at, so a held job keeps its original place in
	// line. Must be before expires_at.
	StartAfter    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=start_after,json=startAfter,proto3,oneof" json:"start_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuedJobInput) Reset() {
	*x = QueuedJobInput{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuedJobInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuedJobInput) ProtoMessage() {}

func (x *QueuedJobInput) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuedJobInput.ProtoReflect.Descriptor instead.
func (*QueuedJobInput) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueuedJobInput) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *QueuedJobInput) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *QueuedJobInput) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *QueuedJobInput) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *QueuedJobInput) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *QueuedJobInput) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *QueuedJobInput) GetRestartPolicy() JobRestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return JobRestartPolicy_JRP_ON_FAILURE
}

func (x *QueuedJobInput) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *QueuedJobInput) GetWebhooks() []*WebhookConfig {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *QueuedJobInput) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueuedJobInput) GetStartAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAfter
	}
	return nil
}

type QueuedJob struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId *string                `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Status  QueuedJobStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=livekit.QueuedJobStatus" json:"status,omitempty"`
	Input   *QueuedJobInput        `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	// Set once dispatch is invoked; the join point into the dispatch APIs.
	DispatchId string `protobuf:"bytes,5,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	// Set once the room is created.
	RoomId string `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// JSON the agent writes back before exiting; opaque to the queue and carried
	// on the terminal webhook.
	Result string `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	// Set on FAILED, including exhaustion of infra retries.
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Dispatch attempts made by the queue. Counts infra-level retries before a
	// dispatch succeeds, not agent-side failures.
	Attempts      int32                  `protobuf:"varint,9,opt,name=attempts,proto3" json:"attempts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DispatchedAt  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuedJob) Reset() {
	*x = QueuedJob{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuedJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuedJob) ProtoMessage() {}

func (x *QueuedJob) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuedJob.ProtoReflect.Descriptor instead.
func (*QueuedJob) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{1}
}

func (x *QueuedJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueuedJob) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *QueuedJob) GetStatus() QueuedJobStatus {
	if x != nil {
		return x.Status
	}
	return QueuedJobStatus_QUEUED_JOB_STATUS_UNSPECIFIED
}

func (x *QueuedJob) GetInput() *QueuedJobInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *QueuedJob) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *QueuedJob) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *QueuedJob) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *QueuedJob) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueuedJob) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *QueuedJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QueuedJob) GetDispatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DispatchedAt
	}
	return nil
}

func (x *QueuedJob) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type JobGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A paused group admits nothing; jobs already in flight run to completion.
	Paused    bool                    `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	CreatedAt *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Counts    []*JobGroup_StatusCount `protobuf:"bytes,4,rep,name=counts,proto3" json:"counts,omitempty"`
	// Jobs from this group running at once, as set when the group was created.
	// Zero means the dispatcher default applies.
	ConcurrencyLimit uint32 `protobuf:"varint,5,opt,name=concurrency_limit,json=concurrencyLimit,proto3" json:"concurrency_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobGroup) Reset() {
	*x = JobGroup{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGroup) ProtoMessage() {}

func (x *JobGroup) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGroup.ProtoReflect.Descriptor instead.
func (*JobGroup) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{2}
}

func (x *JobGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobGroup) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *JobGroup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobGroup) GetCounts() []*JobGroup_StatusCount {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *JobGroup) GetConcurrencyLimit() uint32 {
	if x != nil {
		return x.ConcurrencyLimit
	}
	return 0
}

// One limit over a slice of the project's queued traffic. A job is evaluated
// against every limit it matches and the smallest remaining budget wins.
//
// These bound what this queue admits. They do not bound sessions started
// outside it, including direct AgentDispatchService.CreateDispatch calls, so
// they are not a cap on an agent's total concurrency.
type DispatchLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope DispatchLimitScope     `protobuf:"varint,1,opt,name=scope,proto3,enum=livekit.DispatchLimitScope" json:"scope,omitempty"`
	// Which value of the scoped attribute this limit covers. Empty with a scope
	// set means every distinct value gets its own budget of this size, so one
	// rule can cover all agents or all label values without enumerating them.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// SCOPE_LABEL only: which QueuedJobInput.labels key to slice on.
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// Jobs from this scope running at once. Unset is unlimited; 0 blocks the
	// scope without touching its jobs.
	MaxConcurrent *uint32 `protobuf:"varint,4,opt,name=max_concurrent,json=maxConcurrent,proto3,oneof" json:"max_concurrent,omitempty"`
	// Dispatch starts allowed in any rolling 60 seconds - not calendar minutes.
	// The scheduler releases this budget in slices across admission rounds, so a
	// minute's worth never lands at once. Unset is unrated.
	MaxStartsPerMinute *uint32 `protobuf:"varint,5,opt,name=max_starts_per_minute,json=maxStartsPerMinute,proto3,oneof" json:"max_starts_per_minute,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DispatchLimit) Reset() {
	*x = DispatchLimit{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchLimit) ProtoMessage() {}

func (x *DispatchLimit) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchLimit.ProtoReflect.Descriptor instead.
func (*DispatchLimit) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchLimit) GetScope() DispatchLimitScope {
	if x != nil {
		return x.Scope
	}
	return DispatchLimitScope_DISPATCH_LIMIT_SCOPE_UNSPECIFIED
}

func (x *DispatchLimit) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DispatchLimit) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DispatchLimit) GetMaxConcurrent() uint32 {
	if x != nil && x.MaxConcurrent != nil {
		return *x.MaxConcurrent
	}
	return 0
}

func (x *DispatchLimit) GetMaxStartsPerMinute() uint32 {
	if x != nil && x.MaxStartsPerMinute != nil {
		return *x.MaxStartsPerMinute
	}
	return 0
}

type DispatchQueueConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The queue stops admitting while free project capacity would fall below
	// this. Everything else the project runs - sessions a user started, direct
	// AgentDispatchService.CreateDispatch calls, anything not from this queue -
	// draws on the same capacity, and this is what the queue leaves for it.
	//
	// The asymmetry is the point: a queued job that cannot get capacity waits,
	// which is what the queue is for. A request from anywhere else has nowhere
	// to wait - it fails with quota exceeded. So the queue must never take the
	// project's last capacity, however much it still has to drain.
	//
	// Size it to the demand you cannot afford to reject, NOT to the peak
	// concurrency of that other work - admission already reads capacity
	// REMAINING, so steady-state load lowers what the queue may take on its
	// own. A project starting 5 sessions/sec wants roughly 10-20 here even if
	// it runs 500 at once.
	MinFreeCapacity uint32           `protobuf:"varint,1,opt,name=min_free_capacity,json=minFreeCapacity,proto3" json:"min_free_capacity,omitempty"`
	Limits          []*DispatchLimit `protobuf:"bytes,2,rep,name=limits,proto3" json:"limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DispatchQueueConfig) Reset() {
	*x = DispatchQueueConfig{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchQueueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchQueueConfig) ProtoMessage() {}

func (x *DispatchQueueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchQueueConfig.ProtoReflect.Descriptor instead.
func (*DispatchQueueConfig) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchQueueConfig) GetMinFreeCapacity() uint32 {
	if x != nil {
		return x.MinFreeCapacity
	}
	return 0
}

func (x *DispatchQueueConfig) GetLimits() []*DispatchLimit {
	if x != nil {
		return x.Limits
	}
	return nil
}

type AddJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Up to 1,000 per request; clients loop to add more.
	Jobs []*QueuedJobInput `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// Attach every job in this request to a group, created on first use.
	GroupId *string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	// Jobs from this group to run at once. Applied when the group is created and
	// ignored on later adds to the same group. Unset uses the dispatcher
	// default. Group limits live here rather than in DispatchQueueConfig because
	// groups are short-lived and would otherwise churn the project config.
	GroupConcurrencyLimit *uint32 `protobuf:"varint,3,opt,name=group_concurrency_limit,json=groupConcurrencyLimit,proto3,oneof" json:"group_concurrency_limit,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddJobsRequest) Reset() {
	*x = AddJobsRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddJobsRequest) ProtoMessage() {}

func (x *AddJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddJobsRequest.ProtoReflect.Descriptor instead.
func (*AddJobsRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{5}
}

func (x *AddJobsRequest) GetJobs() []*QueuedJobInput {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *AddJobsRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *AddJobsRequest) GetGroupConcurrencyLimit() uint32 {
	if x != nil && x.GroupConcurrencyLimit != nil {
		return *x.GroupConcurrencyLimit
	}
	return 0
}

type AddJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Same order and length as the request. Validation is atomic: if any input
	// is invalid nothing is enqueued and the error enumerates every bad entry,
	// so a rejected batch is safe to fix and resend in one pass. An input whose
	// idempotency_key already existed yields the pre-existing job unchanged.
	Jobs          []*QueuedJob `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddJobsResponse) Reset() {
	*x = AddJobsResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddJobsResponse) ProtoMessage() {}

func (x *AddJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddJobsResponse.ProtoReflect.Descriptor instead.
func (*AddJobsResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{6}
}

func (x *AddJobsResponse) GetJobs() []*QueuedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *QueuedJob             `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobResponse) GetJob() *QueuedJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *string                `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Status        *QueuedJobStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=livekit.QueuedJobStatus,oneof" json:"status,omitempty"`
	PageToken     *TokenPagination       `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	PageSize      *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{9}
}

func (x *ListJobsRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *ListJobsRequest) GetStatus() QueuedJobStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return QueuedJobStatus_QUEUED_JOB_STATUS_UNSPECIFIED
}

func (x *ListJobsRequest) GetPageToken() *TokenPagination {
	if x != nil {
		return x.PageToken
	}
	return nil
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*QueuedJob           `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken *TokenPagination       `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{10}
}

func (x *ListJobsResponse) GetJobs() []*QueuedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() *TokenPagination {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

// Cancels a job that has not been admitted yet (QUEUED -> CANCELLED). A job
// already DISPATCHING or RUNNING is left alone; tear down the live session
// through DeleteDispatch or the room APIs instead.
type RemoveJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveJobRequest) Reset() {
	*x = RemoveJobRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveJobRequest) ProtoMessage() {}

func (x *RemoveJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveJobRequest.ProtoReflect.Descriptor instead.
func (*RemoveJobRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RemoveJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveJobResponse) Reset() {
	*x = RemoveJobResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveJobResponse) ProtoMessage() {}

func (x *RemoveJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveJobResponse.ProtoReflect.Descriptor instead.
func (*RemoveJobResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{12}
}

// Re-queues jobs in a FAILED or EXPIRED state, reusing their rows and
// idempotency keys instead of minting new jobs. Jobs in any other state are
// returned untouched.
type RetryJobsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	JobIds []string               `protobuf:"bytes,1,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	// Replaces expires_at on the retried jobs.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	// Replaces start_after on the retried jobs, to hold a retry back rather than
	// re-queueing it immediately. Unset clears any start_after the job carried,
	// since the original hold has already elapsed.
	StartAfter    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_after,json=startAfter,proto3,oneof" json:"start_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJobsRequest) Reset() {
	*x = RetryJobsRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJobsRequest) ProtoMessage() {}

func (x *RetryJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJobsRequest.ProtoReflect.Descriptor instead.
func (*RetryJobsRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{13}
}

func (x *RetryJobsRequest) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

func (x *RetryJobsRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RetryJobsRequest) GetStartAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAfter
	}
	return nil
}

type RetryJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*QueuedJob           `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJobsResponse) Reset() {
	*x = RetryJobsResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJobsResponse) ProtoMessage() {}

func (x *RetryJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJobsResponse.ProtoReflect.Descriptor instead.
func (*RetryJobsResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{14}
}

func (x *RetryJobsResponse) GetJobs() []*QueuedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ListJobGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobGroupsRequest) Reset() {
	*x = ListJobGroupsRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobGroupsRequest) ProtoMessage() {}

func (x *ListJobGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListJobGroupsRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{15}
}

type ListJobGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*JobGroup            `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobGroupsResponse) Reset() {
	*x = ListJobGroupsResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobGroupsResponse) ProtoMessage() {}

func (x *ListJobGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListJobGroupsResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{16}
}

func (x *ListJobGroupsResponse) GetGroups() []*JobGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// On every group operation below, an unset group_id applies the operation at
// project scope, across grouped and ungrouped jobs alike.
type PauseJobGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *string                `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseJobGroupRequest) Reset() {
	*x = PauseJobGroupRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseJobGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseJobGroupRequest) ProtoMessage() {}

func (x *PauseJobGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseJobGroupRequest.ProtoReflect.Descriptor instead.
func (*PauseJobGroupRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{17}
}

func (x *PauseJobGroupRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

type PauseJobGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseJobGroupResponse) Reset() {
	*x = PauseJobGroupResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseJobGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseJobGroupResponse) ProtoMessage() {}

func (x *PauseJobGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseJobGroupResponse.ProtoReflect.Descriptor instead.
func (*PauseJobGroupResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{18}
}

type ResumeJobGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *string                `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJobGroupRequest) Reset() {
	*x = ResumeJobGroupRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJobGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJobGroupRequest) ProtoMessage() {}

func (x *ResumeJobGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJobGroupRequest.ProtoReflect.Descriptor instead.
func (*ResumeJobGroupRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{19}
}

func (x *ResumeJobGroupRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

type ResumeJobGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJobGroupResponse) Reset() {
	*x = ResumeJobGroupResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJobGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJobGroupResponse) ProtoMessage() {}

func (x *ResumeJobGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJobGroupResponse.ProtoReflect.Descriptor instead.
func (*ResumeJobGroupResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{20}
}

// Cancels the queued jobs in the group; jobs already in flight run to
// completion.
type CancelJobGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *string                `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobGroupRequest) Reset() {
	*x = CancelJobGroupRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobGroupRequest) ProtoMessage() {}

func (x *CancelJobGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobGroupRequest.ProtoReflect.Descriptor instead.
func (*CancelJobGroupRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{21}
}

func (x *CancelJobGroupRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

type CancelJobGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobGroupResponse) Reset() {
	*x = CancelJobGroupResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobGroupResponse) ProtoMessage() {}

func (x *CancelJobGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobGroupResponse.ProtoReflect.Descriptor instead.
func (*CancelJobGroupResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{22}
}

// Cancels the remaining queued jobs and hides the group and its terminal jobs
// from listings. Rows are kept for the retention window.
type DeleteJobGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *string                `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobGroupRequest) Reset() {
	*x = DeleteJobGroupRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobGroupRequest) ProtoMessage() {}

func (x *DeleteJobGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobGroupRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteJobGroupRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

type DeleteJobGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobGroupResponse) Reset() {
	*x = DeleteJobGroupResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobGroupResponse) ProtoMessage() {}

func (x *DeleteJobGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobGroupResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{24}
}

type GetDispatchQueueConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDispatchQueueConfigRequest) Reset() {
	*x = GetDispatchQueueConfigRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDispatchQueueConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDispatchQueueConfigRequest) ProtoMessage() {}

func (x *GetDispatchQueueConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDispatchQueueConfigRequest.ProtoReflect.Descriptor instead.
func (*GetDispatchQueueConfigRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{25}
}

type GetDispatchQueueConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *DispatchQueueConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDispatchQueueConfigResponse) Reset() {
	*x = GetDispatchQueueConfigResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDispatchQueueConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDispatchQueueConfigResponse) ProtoMessage() {}

func (x *GetDispatchQueueConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDispatchQueueConfigResponse.ProtoReflect.Descriptor instead.
func (*GetDispatchQueueConfigResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{26}
}

func (x *GetDispatchQueueConfigResponse) GetConfig() *DispatchQueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Replaces the stored config wholesale, so an omitted limit is a removed
// limit. Read-modify-write to change one field.
type UpdateDispatchQueueConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *DispatchQueueConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDispatchQueueConfigRequest) Reset() {
	*x = UpdateDispatchQueueConfigRequest{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDispatchQueueConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDispatchQueueConfigRequest) ProtoMessage() {}

func (x *UpdateDispatchQueueConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDispatchQueueConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateDispatchQueueConfigRequest) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateDispatchQueueConfigRequest) GetConfig() *DispatchQueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateDispatchQueueConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *DispatchQueueConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDispatchQueueConfigResponse) Reset() {
	*x = UpdateDispatchQueueConfigResponse{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDispatchQueueConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDispatchQueueConfigResponse) ProtoMessage() {}

func (x *UpdateDispatchQueueConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDispatchQueueConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateDispatchQueueConfigResponse) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateDispatchQueueConfigResponse) GetConfig() *DispatchQueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Proto3 forbids enum map keys, so counts by status are a repeated pair.
type JobGroup_StatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        QueuedJobStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=livekit.QueuedJobStatus" json:"status,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGroup_StatusCount) Reset() {
	*x = JobGroup_StatusCount{}
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGroup_StatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGroup_StatusCount) ProtoMessage() {}

func (x *JobGroup_StatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_dispatch_queue_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGroup_StatusCount.ProtoReflect.Descriptor instead.
func (*JobGroup_StatusCount) Descriptor() ([]byte, []int) {
	return file_livekit_agent_dispatch_queue_proto_rawDescGZIP(), []int{2, 0}
}

func (x *JobGroup_StatusCount) GetStatus() QueuedJobStatus {
	if x != nil {
		return x.Status
	}
	return QueuedJobStatus_QUEUED_JOB_STATUS_UNSPECIFIED
}

func (x *JobGroup_StatusCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_livekit_agent_dispatch_queue_proto protoreflect.FileDescriptor

const file_livekit_agent_dispatch_queue_proto_rawDesc = "" +
	"\n" +
	"\"livekit_agent_dispatch_queue.proto\x12\alivekit\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1clivekit_agent_dispatch.proto\x1a\x14livekit_models.proto\x1a\x14logger/options.proto\"\xd2\x05\n" +
	"\x0eQueuedJobInput\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\bmetadata\x18\x04 \x01(\tB\x03\xc0P\x01R\bmetadata\x12L\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2'.livekit.QueuedJobInput.AttributesEntryB\x03\xc0P\x01R\n" +
	"attributes\x12\x1e\n" +
	"\n" +
	"deployment\x18\x06 \x01(\tR\n" +
	"deployment\x12@\n" +
	"\x0erestart_policy\x18\a \x01(\x0e2\x19.livekit.JobRestartPolicyR\rrestartPolicy\x12>\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x122\n" +
	"\bwebhooks\x18\t \x03(\v2\x16.livekit.WebhookConfigR\bwebhooks\x12;\n" +
	"\x06labels\x18\n" +
	" \x03(\v2#.livekit.QueuedJobInput.LabelsEntryR\x06labels\x12@\n" +
	"\vstart_after\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"startAfter\x88\x01\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_expires_atB\x0e\n" +
	"\f_start_after\"\x9d\x04\n" +
	"\tQueuedJob\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaP\x05jobIDR\x02id\x12*\n" +
	"\bgroup_id\x18\x02 \x01(\tB\n" +
	"\xbaP\agroupIDH\x00R\agroupId\x88\x01\x01\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.livekit.QueuedJobStatusR\x06status\x12-\n" +
	"\x05input\x18\x04 \x01(\v2\x17.livekit.QueuedJobInputR\x05input\x12.\n" +
	"\vdispatch_id\x18\x05 \x01(\tB\r\xbaP\n" +
	"dispatchIDR\n" +
	"dispatchId\x12\"\n" +
	"\aroom_id\x18\x06 \x01(\tB\t\xbaP\x06roomIDR\x06roomId\x12\x1b\n" +
	"\x06result\x18\a \x01(\tB\x03\xc0P\x01R\x06result\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1a\n" +
	"\battempts\x18\t \x01(\x05R\battempts\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\rdispatched_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fdispatchedAt\x12=\n" +
	"\fcompleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAtB\v\n" +
	"\t_group_id\"\xb4\x02\n" +
	"\bJobGroup\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaP\agroupIDR\x02id\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\x06counts\x18\x04 \x03(\v2\x1d.livekit.JobGroup.StatusCountR\x06counts\x12+\n" +
	"\x11concurrency_limit\x18\x05 \x01(\rR\x10concurrencyLimit\x1aU\n" +
	"\vStatusCount\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.livekit.QueuedJobStatusR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xfb\x01\n" +
	"\rDispatchLimit\x121\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x1b.livekit.DispatchLimitScopeR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12*\n" +
	"\x0emax_concurrent\x18\x04 \x01(\rH\x00R\rmaxConcurrent\x88\x01\x01\x126\n" +
	"\x15max_starts_per_minute\x18\x05 \x01(\rH\x01R\x12maxStartsPerMinute\x88\x01\x01B\x11\n" +
	"\x0f_max_concurrentB\x18\n" +
	"\x16_max_starts_per_minute\"q\n" +
	"\x13DispatchQueueConfig\x12*\n" +
	"\x11min_free_capacity\x18\x01 \x01(\rR\x0fminFreeCapacity\x12.\n" +
	"\x06limits\x18\x02 \x03(\v2\x16.livekit.DispatchLimitR\x06limits\"\xcf\x01\n" +
	"\x0eAddJobsRequest\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.livekit.QueuedJobInputR\x04jobs\x12*\n" +
	"\bgroup_id\x18\x02 \x01(\tB\n" +
	"\xbaP\agroupIDH\x00R\agroupId\x88\x01\x01\x12;\n" +
	"\x17group_concurrency_limit\x18\x03 \x01(\rH\x01R\x15groupConcurrencyLimit\x88\x01\x01B\v\n" +
	"\t_group_idB\x1a\n" +
	"\x18_group_concurrency_limit\"9\n" +
	"\x0fAddJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.livekit.QueuedJobR\x04jobs\"0\n" +
	"\rGetJobRequest\x12\x1f\n" +
	"\x06job_id\x18\x01 \x01(\tB\b\xbaP\x05jobIDR\x05jobId\"6\n" +
	"\x0eGetJobResponse\x12$\n" +
	"\x03job\x18\x01 \x01(\v2\x12.livekit.QueuedJobR\x03job\"\x89\x02\n" +
	"\x0fListJobsRequest\x12*\n" +
	"\bgroup_id\x18\x01 \x01(\tB\n" +
	"\xbaP\agroupIDH\x00R\agroupId\x88\x01\x01\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.livekit.QueuedJobStatusH\x01R\x06status\x88\x01\x01\x12<\n" +
	"\n" +
	"page_token\x18\x03 \x01(\v2\x18.livekit.TokenPaginationH\x02R\tpageToken\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05H\x03R\bpageSize\x88\x01\x01B\v\n" +
	"\t_group_idB\t\n" +
	"\a_statusB\r\n" +
	"\v_page_tokenB\f\n" +
	"\n" +
	"_page_size\"|\n" +
	"\x10ListJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.livekit.QueuedJobR\x04jobs\x12@\n" +
	"\x0fnext_page_token\x18\x02 \x01(\v2\x18.livekit.TokenPaginationR\rnextPageToken\"3\n" +
	"\x10RemoveJobRequest\x12\x1f\n" +
	"\x06job_id\x18\x01 \x01(\tB\b\xbaP\x05jobIDR\x05jobId\"\x13\n" +
	"\x11RemoveJobResponse\"\xd7\x01\n" +
	"\x10RetryJobsRequest\x12\"\n" +
	"\ajob_ids\x18\x01 \x03(\tB\t\xbaP\x06jobIDsR\x06jobIds\x12>\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x12@\n" +
	"\vstart_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"startAfter\x88\x01\x01B\r\n" +
	"\v_expires_atB\x0e\n" +
	"\f_start_after\";\n" +
	"\x11RetryJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.livekit.QueuedJobR\x04jobs\"\x16\n" +
	"\x14ListJobGroupsRequest\"B\n" +
	"\x15ListJobGroupsResponse\x12)\n" +
	"\x06groups\x18\x01 \x03(\v2\x11.livekit.JobGroupR\x06groups\"O\n" +
	"\x14PauseJobGroupRequest\x12*\n" +
	"\bgroup_id\x18\x01 \x01(\tB\n" +
	"\xbaP\agroupIDH\x00R\agroupId\x88\x01\x01B\v\n" +
	"\t_group_id\"\x17\n" +
	"\x15PauseJobGroupResponse\"P\n" +
	"\x15ResumeJobGroupRequest\x12*\n" +
	"\bgroup_id\x18\x01 \x01(\tB\n" +
	"\xbaP\agroupIDH\x00R\agroupId\x88\x01\x01B\v\n" +
	"\t_group_id\"\x18\n" +
	"\x16ResumeJobGroupResponse\"P\n" +
	"\x15CancelJobGroupRequest\x12*\n" +
	"\bgroup_id\x18\x01 \x01(\tB\n" +
	"\xbaP\agroupIDH\x00R\agroupId\x88\x01\x01B\v\n" +
	"\t_group_id\"\x18\n" +
	"\x16CancelJobGroupResponse\"P\n" +
	"\x15DeleteJobGroupRequest\x12*\n" +
	"\bgroup_id\x18\x01 \x01(\tB\n" +
	"\xbaP\agroupIDH\x00R\agroupId\x88\x01\x01B\v\n" +
	"\t_group_id\"\x18\n" +
	"\x16DeleteJobGroupResponse\"\x1f\n" +
	"\x1dGetDispatchQueueConfigRequest\"V\n" +
	"\x1eGetDispatchQueueConfigResponse\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.livekit.DispatchQueueConfigR\x06config\"X\n" +
	" UpdateDispatchQueueConfigRequest\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.livekit.DispatchQueueConfigR\x06config\"Y\n" +
	"!UpdateDispatchQueueConfigResponse\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.livekit.DispatchQueueConfigR\x06config*\x93\x02\n" +
	"\x0fQueuedJobStatus\x12!\n" +
	"\x1dQUEUED_JOB_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18QUEUED_JOB_STATUS_QUEUED\x10\x01\x12!\n" +
	"\x1dQUEUED_JOB_STATUS_DISPATCHING\x10\x02\x12\x1d\n" +
	"\x19QUEUED_JOB_STATUS_RUNNING\x10\x03\x12\x1f\n" +
	"\x1bQUEUED_JOB_STATUS_SUCCEEDED\x10\x04\x12\x1c\n" +
	"\x18QUEUED_JOB_STATUS_FAILED\x10\x05\x12\x1f\n" +
	"\x1bQUEUED_JOB_STATUS_CANCELLED\x10\x06\x12\x1d\n" +
	"\x19QUEUED_JOB_STATUS_EXPIRED\x10\a*z\n" +
	"\x12DispatchLimitScope\x12$\n" +
	" DISPATCH_LIMIT_SCOPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDISPATCH_LIMIT_SCOPE_AGENT\x10\x01\x12\x1e\n" +
	"\x1aDISPATCH_LIMIT_SCOPE_LABEL\x10\x022\xce\a\n" +
	"\x12AgentDispatchQueue\x12<\n" +
	"\aAddJobs\x12\x17.livekit.AddJobsRequest\x1a\x18.livekit.AddJobsResponse\x129\n" +
	"\x06GetJob\x12\x16.livekit.GetJobRequest\x1a\x17.livekit.GetJobResponse\x12?\n" +
	"\bListJobs\x12\x18.livekit.ListJobsRequest\x1a\x19.livekit.ListJobsResponse\x12B\n" +
	"\tRemoveJob\x12\x19.livekit.RemoveJobRequest\x1a\x1a.livekit.RemoveJobResponse\x12B\n" +
	"\tRetryJobs\x12\x19.livekit.RetryJobsRequest\x1a\x1a.livekit.RetryJobsResponse\x12N\n" +
	"\rListJobGroups\x12\x1d.livekit.ListJobGroupsRequest\x1a\x1e.livekit.ListJobGroupsResponse\x12N\n" +
	"\rPauseJobGroup\x12\x1d.livekit.PauseJobGroupRequest\x1a\x1e.livekit.PauseJobGroupResponse\x12Q\n" +
	"\x0eResumeJobGroup\x12\x1e.livekit.ResumeJobGroupRequest\x1a\x1f.livekit.ResumeJobGroupResponse\x12Q\n" +
	"\x0eCancelJobGroup\x12\x1e.livekit.CancelJobGroupRequest\x1a\x1f.livekit.CancelJobGroupResponse\x12Q\n" +
	"\x0eDeleteJobGroup\x12\x1e.livekit.DeleteJobGroupRequest\x1a\x1f.livekit.DeleteJobGroupResponse\x12i\n" +
	"\x16GetDispatchQueueConfig\x12&.livekit.GetDispatchQueueConfigRequest\x1a'.livekit.GetDispatchQueueConfigResponse\x12r\n" +
	"\x19UpdateDispatchQueueConfig\x12).livekit.UpdateDispatchQueueConfigRequest\x1a*.livekit.UpdateDispatchQueueConfigResponseBFZ#github.com/livekit/protocol/livekit\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3"

var (
	file_livekit_agent_dispatch_queue_proto_rawDescOnce sync.Once
	file_livekit_agent_dispatch_queue_proto_rawDescData []byte
)

func file_livekit_agent_dispatch_queue_proto_rawDescGZIP() []byte {
	file_livekit_agent_dispatch_queue_proto_rawDescOnce.Do(func() {
		file_livekit_agent_dispatch_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livekit_agent_dispatch_queue_proto_rawDesc), len(file_livekit_agent_dispatch_queue_proto_rawDesc)))
	})
	return file_livekit_agent_dispatch_queue_proto_rawDescData
}

var file_livekit_agent_dispatch_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_livekit_agent_dispatch_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_livekit_agent_dispatch_queue_proto_goTypes = []any{
	(QueuedJobStatus)(0),                      // 0: livekit.QueuedJobStatus
	(DispatchLimitScope)(0),                   // 1: livekit.DispatchLimitScope
	(*QueuedJobInput)(nil),                    // 2: livekit.QueuedJobInput
	(*QueuedJob)(nil),                         // 3: livekit.QueuedJob
	(*JobGroup)(nil),                          // 4: livekit.JobGroup
	(*DispatchLimit)(nil),                     // 5: livekit.DispatchLimit
	(*DispatchQueueConfig)(nil),               // 6: livekit.DispatchQueueConfig
	(*AddJobsRequest)(nil),                    // 7: livekit.AddJobsRequest
	(*AddJobsResponse)(nil),                   // 8: livekit.AddJobsResponse
	(*GetJobRequest)(nil),                     // 9: livekit.GetJobRequest
	(*GetJobResponse)(nil),                    // 10: livekit.GetJobResponse
	(*ListJobsRequest)(nil),                   // 11: livekit.ListJobsRequest
	(*ListJobsResponse)(nil),                  // 12: livekit.ListJobsResponse
	(*RemoveJobRequest)(nil),                  // 13: livekit.RemoveJobRequest
	(*RemoveJobResponse)(nil),                 // 14: livekit.RemoveJobResponse
	(*RetryJobsRequest)(nil),                  // 15: livekit.RetryJobsRequest
	(*RetryJobsResponse)(nil),                 // 16: livekit.RetryJobsResponse
	(*ListJobGroupsRequest)(nil),              // 17: livekit.ListJobGroupsRequest
	(*ListJobGroupsResponse)(nil),             // 18: livekit.ListJobGroupsResponse
	(*PauseJobGroupRequest)(nil),              // 19: livekit.PauseJobGroupRequest
	(*PauseJobGroupResponse)(nil),             // 20: livekit.PauseJobGroupResponse
	(*ResumeJobGroupRequest)(nil),             // 21: livekit.ResumeJobGroupRequest
	(*ResumeJobGroupResponse)(nil),            // 22: livekit.ResumeJobGroupResponse
	(*CancelJobGroupRequest)(nil),             // 23: livekit.CancelJobGroupRequest
	(*CancelJobGroupResponse)(nil),            // 24: livekit.CancelJobGroupResponse
	(*DeleteJobGroupRequest)(nil),             // 25: livekit.DeleteJobGroupRequest
	(*DeleteJobGroupResponse)(nil),            // 26: livekit.DeleteJobGroupResponse
	(*GetDispatchQueueConfigRequest)(nil),     // 27: livekit.GetDispatchQueueConfigRequest
	(*GetDispatchQueueConfigResponse)(nil),    // 28: livekit.GetDispatchQueueConfigResponse
	(*UpdateDispatchQueueConfigRequest)(nil),  // 29: livekit.UpdateDispatchQueueConfigRequest
	(*UpdateDispatchQueueConfigResponse)(nil), // 30: livekit.UpdateDispatchQueueConfigResponse
	nil,                           // 31: livekit.QueuedJobInput.AttributesEntry
	nil,                           // 32: livekit.QueuedJobInput.LabelsEntry
	(*JobGroup_StatusCount)(nil),  // 33: livekit.JobGroup.StatusCount
	(JobRestartPolicy)(0),         // 34: livekit.JobRestartPolicy
	(*timestamppb.Timestamp)(nil), // 35: google.protobuf.Timestamp
	(*WebhookConfig)(nil),         // 36: livekit.WebhookConfig
	(*TokenPagination)(nil),       // 37: livekit.TokenPagination
}
var file_livekit_agent_dispatch_queue_proto_depIdxs = []int32{
	31, // 0: livekit.QueuedJobInput.attributes:type_name -> livekit.QueuedJobInput.AttributesEntry
	34, // 1: livekit.QueuedJobInput.restart_policy:type_name -> livekit.JobRestartPolicy
	35, // 2: livekit.QueuedJobInput.expires_at:type_name -> google.protobuf.Timestamp
	36, // 3: livekit.QueuedJobInput.webhooks:type_name -> livekit.WebhookConfig
	32, // 4: livekit.QueuedJobInput.labels:type_name -> livekit.QueuedJobInput.LabelsEntry
	35, // 5: livekit.QueuedJobInput.start_after:type_name -> google.protobuf.Timestamp
	0,  // 6: livekit.QueuedJob.status:type_name -> livekit.QueuedJobStatus
	2,  // 7: livekit.QueuedJob.input:type_name -> livekit.QueuedJobInput
	35, // 8: livekit.QueuedJob.created_at:type_name -> google.protobuf.Timestamp
	35, // 9: livekit.QueuedJob.dispatched_at:type_name -> google.protobuf.Timestamp
	35, // 10: livekit.QueuedJob.completed_at:type_name -> google.protobuf.Timestamp
	35, // 11: livekit.JobGroup.created_at:type_name -> google.protobuf.Timestamp
	33, // 12: livekit.JobGroup.counts:type_name -> livekit.JobGroup.StatusCount
	1,  // 13: livekit.DispatchLimit.scope:type_name -> livekit.DispatchLimitScope
	5,  // 14: livekit.DispatchQueueConfig.limits:type_name -> livekit.DispatchLimit
	2,  // 15: livekit.AddJobsRequest.jobs:type_name -> livekit.QueuedJobInput
	3,  // 16: livekit.AddJobsResponse.jobs:type_name -> livekit.QueuedJob
	3,  // 17: livekit.GetJobResponse.job:type_name -> livekit.QueuedJob
	0,  // 18: livekit.ListJobsRequest.status:type_name -> livekit.QueuedJobStatus
	37, // 19: livekit.ListJobsRequest.page_token:type_name -> livekit.TokenPagination
	3,  // 20: livekit.ListJobsResponse.jobs:type_name -> livekit.QueuedJob
	37, // 21: livekit.ListJobsResponse.next_page_token:type_name -> livekit.TokenPagination
	35, // 22: livekit.RetryJobsRequest.expires_at:type_name -> google.protobuf.Timestamp
	35, // 23: livekit.RetryJobsRequest.start_after:type_name -> google.protobuf.Timestamp
	3,  // 24: livekit.RetryJobsResponse.jobs:type_name -> livekit.QueuedJob
	4,  // 25: livekit.ListJobGroupsResponse.groups:type_name -> livekit.JobGroup
	6,  // 26: livekit.GetDispatchQueueConfigResponse.config:type_name -> livekit.DispatchQueueConfig
	6,  // 27: livekit.UpdateDispatchQueueConfigRequest.config:type_name -> livekit.DispatchQueueConfig
	6,  // 28: livekit.UpdateDispatchQueueConfigResponse.config:type_name -> livekit.DispatchQueueConfig
	0,  // 29: livekit.JobGroup.StatusCount.status:type_name -> livekit.QueuedJobStatus
	7,  // 30: livekit.AgentDispatchQueue.AddJobs:input_type -> livekit.AddJobsRequest
	9,  // 31: livekit.AgentDispatchQueue.GetJob:input_type -> livekit.GetJobRequest
	11, // 32: livekit.AgentDispatchQueue.ListJobs:input_type -> livekit.ListJobsRequest
	13, // 33: livekit.AgentDispatchQueue.RemoveJob:input_type -> livekit.RemoveJobRequest
	15, // 34: livekit.AgentDispatchQueue.RetryJobs:input_type -> livekit.RetryJobsRequest
	17, // 35: livekit.AgentDispatchQueue.ListJobGroups:input_type -> livekit.ListJobGroupsRequest
	19, // 36: livekit.AgentDispatchQueue.PauseJobGroup:input_type -> livekit.PauseJobGroupRequest
	21, // 37: livekit.AgentDispatchQueue.ResumeJobGroup:input_type -> livekit.ResumeJobGroupRequest
	23, // 38: livekit.AgentDispatchQueue.CancelJobGroup:input_type -> livekit.CancelJobGroupRequest
	25, // 39: livekit.AgentDispatchQueue.DeleteJobGroup:input_type -> livekit.DeleteJobGroupRequest
	27, // 40: livekit.AgentDispatchQueue.GetDispatchQueueConfig:input_type -> livekit.GetDispatchQueueConfigRequest
	29, // 41: livekit.AgentDispatchQueue.UpdateDispatchQueueConfig:input_type -> livekit.UpdateDispatchQueueConfigRequest
	8,  // 42: livekit.AgentDispatchQueue.AddJobs:output_type -> livekit.AddJobsResponse
	10, // 43: livekit.AgentDispatchQueue.GetJob:output_type -> livekit.GetJobResponse
	12, // 44: livekit.AgentDispatchQueue.ListJobs:output_type -> livekit.ListJobsResponse
	14, // 45: livekit.AgentDispatchQueue.RemoveJob:output_type -> livekit.RemoveJobResponse
	16, // 46: livekit.AgentDispatchQueue.RetryJobs:output_type -> livekit.RetryJobsResponse
	18, // 47: livekit.AgentDispatchQueue.ListJobGroups:output_type -> livekit.ListJobGroupsResponse
	20, // 48: livekit.AgentDispatchQueue.PauseJobGroup:output_type -> livekit.PauseJobGroupResponse
	22, // 49: livekit.AgentDispatchQueue.ResumeJobGroup:output_type -> livekit.ResumeJobGroupResponse
	24, // 50: livekit.AgentDispatchQueue.CancelJobGroup:output_type -> livekit.CancelJobGroupResponse
	26, // 51: livekit.AgentDispatchQueue.DeleteJobGroup:output_type -> livekit.DeleteJobGroupResponse
	28, // 52: livekit.AgentDispatchQueue.GetDispatchQueueConfig:output_type -> livekit.GetDispatchQueueConfigResponse
	30, // 53: livekit.AgentDispatchQueue.UpdateDispatchQueueConfig:output_type -> livekit.UpdateDispatchQueueConfigResponse
	42, // [42:54] is the sub-list for method output_type
	30, // [30:42] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_livekit_agent_dispatch_queue_proto_init() }
func file_livekit_agent_dispatch_queue_proto_init() {
	if File_livekit_agent_dispatch_queue_proto != nil {
		return
	}
	file_livekit_agent_dispatch_proto_init()
	file_livekit_models_proto_init()
	file_livekit_agent_dispatch_queue_proto_msgTypes[0].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[1].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[3].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[5].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[9].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[13].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[17].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[19].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[21].OneofWrappers = []any{}
	file_livekit_agent_dispatch_queue_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livekit_agent_dispatch_queue_proto_rawDesc), len(file_livekit_agent_dispatch_queue_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livekit_agent_dispatch_queue_proto_goTypes,
		DependencyIndexes: file_livekit_agent_dispatch_queue_proto_depIdxs,
		EnumInfos:         file_livekit_agent_dispatch_queue_proto_enumTypes,
		MessageInfos:      file_livekit_agent_dispatch_queue_proto_msgTypes,
	}.Build()
	File_livekit_agent_dispatch_queue_proto = out.File
	file_livekit_agent_dispatch_queue_proto_goTypes = nil
	file_livekit_agent_dispatch_queue_proto_depIdxs = nil
}
